### ISSUE TITLE
create multi-language support in avelino/awesome-go, starting CN

### ISSUE THREAD

**Issue by avelino** [yinggaozhen/awesome-go-cn#333]
How about moving that effort to the awesome-go main repository `README-CN.md`? @yinggaozhen you can continue coordinating this work there (give you access)

**Comment by yinggaozhen** [comment]
Hello, @avelino, I'm sorry that I haven't replied in time due to my busy work recently.

First of all, I am very honored to receive your invitation. To be honest, I am very happy to receive your invitation.

However, in fact, my personal English ability is not very strong (only CET6). Even in the awesome-go-cn project, I also use a lot of machine translation, so the translation quality is not high. So for the official Chinese translation, I'm afraid I can't do it. I'm very sorry!

Finally: Thank you for your attention to the Chinese version. We are looking forward to the official Chinese version in the future!
_______
您好，@avelino ，因为最近工作上比较繁忙，未能及时回复，非常抱歉。
首先非常荣幸能收到您的邀请，说实话能收到您的邀请我是非常高兴的。
但是，事实上，我个人的英语能力并不是很强(只达到了CET6)，即便是 awesome-go-cn 这个项目，我也是大量的采用的机器翻译，所以翻译质量并不高。所以对于官方中文版本翻译，恐怕我无法胜任，非常抱歉！
最后 : 感谢官方对中文版本的重视，非常期待将来的官方中文版！

**Comment by avelino** [comment]
I'm willing to help if you want to take the repository to [awesome-go](https://github.com/avelino/awesome-go)
